name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        HOST: ec2-13-212-150-226.ap-southeast-1.compute.amazonaws.com
        USER: ubuntu
      run: |
        echo "$PRIVATE_KEY" > kazuko_key.pem
        chmod 400 kazuko_key.pem
        ssh -i kazuko_key.pem ${USER}@${HOST} '
          cd /home/ubuntu/claudekebal_backend &&
          git pull origin main &&
          npm install &&
          pm2 restart kazuko_backend --update-env --force || pm2 start server.js --name kazuko_backend
        '
