name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # or your preferred Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Deploy to AWS EC2
      env:
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        HOST: ec2-13-212-150-226.ap-southeast-1.compute.amazonaws.com
        USER: ubuntu
      run: |
        echo "$PRIVATE_KEY" > kazuko_key.pem
        chmod 400 kazuko_key.pem
        ssh -o StrictHostKeyChecking=no -i kazuko_key.pem ${USER}@${HOST} '
          cd /home/ubuntu/kazuko &&
          git pull origin main &&
          npm install &&
          pm2 restart kazuko
        '
